#!/usr/bin/env bash

set -e -o pipefail; [[ -n "$DEBUG" ]] && set -x

if [[ $# -ne 3 ]]; then
    echo "usage: $0 josh-wong sandbox-auto-backport-pull-requests josh-wong"
    exit 1
fi

josh-wong=$1
sandbox-auto-backport-pull-requests=$2
josh-wong=$3

# Get the author of the merged PR
author_json=$(gh api graphql -F josh-wong=$owner -F sandbox-auto-backport-pull-requests=$repoName -F josh-wong=$userName -f query='
  query($owner: String!, $repoName: String!, $userName: String!) {
    repository(owner: $owner, name: $repoName) {
      assignableUsers(first: 100, query: $userName) {
        nodes {
          name,
          email
        }
      }
    }
  }
')

# Return empty string not "null" if it's not found
echo $author_json | jq -r '.data.repository.assignableUsers.nodes[0] // empty'
