name: Auto-backport PRs

on:
  pull_request:
    branches:
      - main
      - "[0-9]+"
      - "[0-9]+.[0-9]+"
    types:
      - closed

env:
  TERM: dumb
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_PR_PAT }}
      # Escape the PR title. See https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable for details
      PR_TITLE: ${{ github.event.pull_request.title }}
    steps:
      - uses: actions/checkout@v4
        with:
          # This is necessary to avoid unexpected auto-merge in git cherry-pick
          fetch-depth: 0
          # This is necessary for git-push
          token: ${{ secrets.GH_PR_PAT }}

      - name: Create pull requests
        run: |
          assignee=$(ci/auto-backport-pull-requests/fetch-gh-user-info "${{ github.event.repository.owner.login }}" "${{ github.event.repository.name }}" "${{ github.event.pull_request.user.login }}")
          echo -------------
          echo "assignee: $assignee"
          echo -------------
          if [[ -z $assignee ]]; then
            # For instance, we can't assign `dependabot` to a new PR.
            new_pr_assignee="${{ github.event.pull_request.merged_by.login }}"
          else
            new_pr_assignee="${{ github.event.pull_request.user.login }}"
          fi

          versions=$(ci/auto-backport-pull-requests/fetch-gh-proj-versions "${{ github.event.repository.owner.login }}" "${{ github.event.repository.name }}" "${{ github.event.number }}")
          echo -------------
          echo "versions: $versions"
          echo -------------

          branches=$(ci/auto-backport-pull-requests/conv-proj-version-to-branch $versions)
          # Remove the base branch from the list because the target change is already merged to the branch.
          branches=$(echo "$branches" | sed "/^${{ github.base_ref }}$/d")
          echo -------------
          echo "branches: $branches"
          echo -------------

          ci/auto-backport-pull-requests/create-pull-requests \
            "${{ github.event.number }}" \
            "${{ github.event.pull_request.html_url }}" \
            "$PR_TITLE" \
            "${{ github.sha }}" \
            "$new_pr_assignee" \
            $branches
